/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "awsf-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "awsf-function": {
      "name": string
      "type": "sst.aws.Function"
    }
    "awsf-public-function": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "awsf-vpc": {
      "type": "sst.aws.Vpc"
    }
    "frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}